### ISSUE TITLE
entries.length undefined

### ISSUE THREAD

**Issue by nlanson** [burkostya/node-unrar#15]
Hello, 

I have an issue when using the archive.list function.

The callback with params err and entries and entires is undefined.

Thanks.

Code:
```
const Unrar =  require('unrar');
const fs = require('fs');
const path = require('path');

function main() {
    let archive = new Unrar('rar.rar');

        archive.list(function(err, entries) {
            for (var i = 0; i < entries.length; i++) {
                var name = entries[i].name;
                var type = entries[i].type
                if (type !== 'File') {
                    fs.mkdirSync(name)
                }
            }
        });

        //console.log(newMangas);

        return true; //Return flag
}

main();
```

Error:
```
for (var i = 0; i < entries.length; i++) {
                                        ^

TypeError: Cannot read property 'length' of undefined
    at C:\path\index.js:10:41
    at C:\path\node_modules\unrar\index.js:27:14
    at C:\path\node_modules\unrar\index.js:88:14
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by burkostya** [comment]
Hi!
Did you solve the issue?

**Comment by nlanson** [comment]
No I did not. I ended up using node-unzipper.

However as a possible solution you could try using for await syntax.

**Comment by burkostya** [comment]
Could you provide a minimal example of `rar.rar`? I will try to reproduce the issue.

**Comment by nlanson** [comment]
Example:
```javascript
const Unrar = require('unrar');

var archive = new Unrar('rar.rar');

archive.list((err, entries) => {
    if (err) console.log(err);

    for (let i=0; i<entries.length; i++) {
        console.log(entries[i].name);
    }
});
```

Error:
```
/config/workspace/unrar/index.js:8
    for (let i=0; i<entries.length; i++) {
                            ^

TypeError: Cannot read property 'length' of undefined
    at /config/workspace/unrar/index.js:8:29
    at /config/workspace/unrar/node_modules/unrar/index.js:27:14
    at /config/workspace/unrar/node_modules/unrar/index.js:88:14
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
```

**Comment by burkostya** [comment]
I'm telling about actual `rar.rar` file. Not the code that reproduces issue.

**Comment by anilovr** [comment]
Any update on this? entries is undefined for a 75MB rar file in Ubuntu.
